# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Saiwing's blog
email: saiwing nothing-between-words yeung at-sign gmail a-dot com
description: > # this means to ignore newlines until "baseurl:"
  Moar stuff here
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://saiwing-yeung.net" # the base hostname & protocol for your site
twitter_username: saiwing_yeung
github_username:  saiwing-yeung

# Build settings
markdown: kramdown
